### ISSUE TITLE
to_matrix() function description

### ISSUE THREAD

**Issue by revolutioncse** [cgebest/APEx#2]
Hi Chang,

Thank you for your previous help. I just wanted to ask if there is anything I can read more about the to_matrix() function. I am struggling to understand how it actually works. I need to read some theory about it. You mentioned a little bit in your paper:

_Let x represent the histogram of the table D over domW (R).
The set of corresponding counting queries {cϕ1 , . . . , cϕL } for
qW can be represented by a matrix W = [w1, . . . ,wL]T of
size L×|domW (R)|. Hence, the answer to each counting query
is cϕi (D) = wi · x and the answer to the workload counting
query is simplyWx._

If there is anything in a bit more detail will be of great help. 

PS: I know this is not an issue. Please feel free to close it.

**Comment by cgebest** [comment]
Thanks for your interest. The to_matix function is to transform the workload in the matrix mechanism. Details of matrix mechanism can be found in reference [27] from our paper.
